services:
  # nginx:
  #   image: "webdevops/php-nginx:8.0-alpine"
  #   volumes:
  #     - D:/Projects/Nginx:/app
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - mvnetwork
  apache:
    image: "webdevops/php-apache:7.2-alpine"
    volumes:
      - D:/Projects/Nginx:/app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mvnetwork
  # nginx:
  #   image: "fathoniadi/nginx-php:deb-7.2-latest"
  #   volumes:
  #     - D:/Projects/Nginx:/var/www/html
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - mvnetwork
      

  mysql:
    image: "mysql:5.7"
    volumes:
      - D:/Projects/Docker/mysql:/home
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - mvnetwork

networks:
  mvnetwork:
