services:
  apache:
    image: "webdevops/php-apache:7.4-alpine"
    volumes:
      - .\php-app:/app
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - mvnetwork

  redis:
    image: "redis:alpine3.18"
    ports:
      - "6379:6379"
    networks:
      - mvnetwork
  mysql:
    image: "mysql:5.7"
    volumes:
      - .\services\mysql\data:/var/lib/mysql
      # - D:/Projects/Docker/mysql:/home
      - .\services\mysql\config\my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      TZ: Asia/Jakarta
    networks:
      - mvnetwork

  api-go:
    build:
      context: .\services\go
    volumes:
      - .\go-app:/app
    ports:
      - "9000:9000"
      - "8081:8081"
      - "8888:8888"
      - "8080:8080"
    networks:
      - mvnetwork
networks:
  mvnetwork:
