services:
  apache:
    image: "webdevops/php-apache:7.4"
    volumes:
      # - .\php-app:/app
      - D:/Projects/PHP:/app
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - mvnetwork

  redis:
    image: "redis:alpine3.18"
    ports:
      - "6379:6379"
    networks:
      - mvnetwork
  mysql:
    image: "mysql:5.7"
    volumes:
      - .\services\mysql\data:/var/lib/mysql
      # - D:/Projects/Docker/mysql:/home
      - .\services\mysql\config\my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      TZ: Asia/Jakarta
    networks:
      - mvnetwork

  api-go:
    build:
      context: .\services\go
    volumes:
      - .\go-app:/app
    ports:
      - "9000:9000"
      - "8081:8081"
      - "8888:8888"
      - "8080:8080"
    networks:
      - mvnetwork

  elasticsearch:
    image: elasticsearch:7.17.17
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - mvnetwork

  apm-server:
    image: elastic/apm-server:7.17.17
    ports:
      - "8200:8200"
    networks:
      - mvnetwork
    # volumes:
    #   - ./apm-server:/usr/share/apm-server
    command: --strict.perms=false

  kibana:
    image: kibana:7.17.17
    ports:
      - "5601:5601"
    networks:
      - mvnetwork
networks:
  mvnetwork:
    driver: bridge
